apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-agent
spec:
  selector:
    matchLabels:
      agent: fluentd
  template:
    metadata:
      labels:
        agent: fluentd
    spec:
      containers:
      - name: fluentd-container
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        
        volumeMounts:
        - name: varlog
          mountPath: /var/log

        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true

      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

      volumes:
      - name: varlog
        hostPath:
          path: /var/log

      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
