---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: container-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: container-2
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: container-3
    image: nginx
