apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: web-server
  template:
    metadata:
      labels:
        tier: web-server
    spec:
      containers:
        - name: web-server-container
          image: eyesoncloud/web-app:v1
